### ISSUE TITLE
Upgrade to Posthog 1.40.0

### ISSUE THREAD

**Issue by stephane-klein** [stephane-klein/posthog-docker-compose-poc#1]
Upgrade to Posthog `1.40.0`: https://posthog.com/blog/the-posthog-array-1-40-0

**Comment by stephane-klein** [comment]
Task :

- [ ] Upgarde to [`redis:6.2.7-alpine`](https://github.com/PostHog/posthog/blob/70f47510ab108aaab4bee28dce7b7832e7968277/docker-compose.hobby.yml#L20)
- [ ] Update redis config: [`command: redis-server --maxmemory-policy allkeys-lru --maxmemory 200mb`](https://github.com/PostHog/posthog/blob/70f47510ab108aaab4bee28dce7b7832e7968277/docker-compose.hobby.yml#L22)
- [ ] Upgrade to `clickhouse/clickhouse-server:22.3`
- [ ] Migrate to `zookeeper:3.7.0`
- [ ] Migrate to `bitnami/kafka:2.8.1-debian-10-r99`
- [ ] Maybe migrate to this kafka config:  
```
        environment:
            KAFKA_BROKER_ID: 1001
            KAFKA_CFG_RESERVED_BROKER_MAX_ID: 1001
            KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
            KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
            KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
            ALLOW_PLAINTEXT_LISTENER: 'true'
```
- [ ] Remove `PRIMARY_DB: 'clickhouse'`
- [ ] Add object storage service
- [ ] Add `asyncmigrationscheck`
